name: First-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print gretings
        run: echo "Valentine is learning GitHub Actions"
      - name: Print goodbye
        run: echo "Done -bye"
